global:
  annotations: {}
  envs: {}
  addReleaseNameToResource: prepend
  ingress:
    enabled: true
    addReleaseNameToHost: prepend
    defaultDomain: localhost
    defaultTlsSecret:
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
      kubernetes.io/ingress.class: "nginx"

  license:
    secret:
      devOps: devops-secret

#############################################################
# pingfederate values
#############################################################

pingfederate-admin:
  enabled: false

  # workload:
  #  type: StatefulSet

  envs:
    # SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles.git
    # SERVER_PROFILE_PATH: getting-started/pingfederate
    OPERATIONAL_MODE: STANDALONE

  services:
    https:
      servicePort: 9999
      containerPort: 9999
      ingressPort: 443
      dataService: true
    engine:
      servicePort: 9031
      containerPort: 9031
      ingressPort: 443
      dataService: true

  ingress:
    hosts:
      - host: pingfederate-admin._defaultDomain_
        paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: https
      - host: pingfederate-engine._defaultDomain_
        paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: engine
    tls:
      - secretName: _defaultTlsSecret_
        hosts:
          - pingfederate-admin._defaultDomain_
          - pingfederate-engine._defaultDomain_

#############################################################
# pingaccess values
#############################################################

pingaccess-admin:
  enabled: false

  # workload:
  #  type: StatefulSet

  envs:
    OPERATIONAL_MODE: STANDALONE

  services:
    https:
      servicePort: 9000
      containerPort: 9000
      ingressPort: 443
      dataService: true
    engine:
      servicePort: 3000
      containerPort: 3000
      ingressPort: 443
      dataService: true

  ingress:
    hosts:
      - host: pingaccess-admin._defaultDomain_
        paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: https
      - host: pingaccess-engine._defaultDomain_
        paths:
        - path: /
          pathType: Prefix
          backend:
            serviceName: engine
    tls:
      - secretName: _defaultTlsSecret_
        hosts:
          - pingaccess-admin._defaultDomain_
          - pingaccess-engine._defaultDomain_

#############################################################
# pingauthorize values
#############################################################

pingauthorize:
  enabled: false

  # workload:
  #  type: StatefulSet

  envs:
    SERVER_PROFILE_URL: https://github.com/mdeller-ping/server-profile-pingauthorize.git
    SERVER_PROFILE_PATH: getting-started

#############################################################
# pingauthorizepap values
#############################################################

pingauthorizepap:
  enabled: false

  # workload:
  #  type: StatefulSet

  envs:
    HTTPS_PORT: "8443"

#############################################################
# pingdirectory values
#############################################################

pingdirectory:
  enabled: false
  name: pingdirectory

  workload:
    type: StatefulSet
    statefulSet:
      persistentvolume:
        volumes:
          out-dir:
            persistentVolumeClaim:
              resources:
                requests:
                  storage: 8Gi

  envs:
    SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles
    SERVER_PROFILE_PATH: baseline/pingdirectory
    MAKELDIF_USERS: "0"

#############################################################
# pingdataconsole values
#############################################################

pingdataconsole:
  enabled: false
  name: pingdataconsole

  envs:
    SERVER_PROFILE_URL: https://github.com/pingidentity/pingidentity-server-profiles
    SERVER_PROFILE_PATH: baseline/pingdataconsole

